# Generated by Django 3.0.5 on 2020-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200412_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
