# Generated by Django 3.0.5 on 2020-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20200412_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateField(default='1/1/20'),
        ),
    ]
