# Generated by Django 3.0.5 on 2020-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20200412_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
